// frontend/src/components/DateTimePanel.tsx
import { useState, useEffect } from 'react';

const DateTimePanel = () => {
  const [currentTime, setCurrentTime] = useState<Date>(new Date());

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentTime(new Date());
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  const formatDateTime = (date: Date): string => {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    const hours = String(date.getHours()).padStart(2, '0');
    const minutes = String(date.getMinutes()).padStart(2, '0');
    const seconds = String(date.getSeconds()).padStart(2, '0');

    return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
  };

  return (
    <div style={{
      fontFamily: 'monospace',
      fontSize: '14px',
      color: 'var(--pob-text-muted)',
      padding: '0.75rem 0'
    }}>
      {formatDateTime(currentTime)}
    </div>
  );
};

export default DateTimePanel;

// frontend/src/components/DateTimePanel.svelte
<script lang="ts">
  let currentTime = $state(new Date());

  function formatDateTime(date: Date): string {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    const hours = String(date.getHours()).padStart(2, '0');
    const minutes = String(date.getMinutes()).padStart(2, '0');
    const seconds = String(date.getSeconds()).padStart(2, '0');

    return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
  }

  $effect(() => {
    const interval = setInterval(() => {
      currentTime = new Date();
    }, 1000);

    return () => clearInterval(interval);
  });
</script>

<div style="font-family: monospace; font-size: 14px; color: var(--pob-text-muted); padding: 0.75rem 0;">
  {formatDateTime(currentTime)}
</div>
