// frontend/src/components/Footer.svelte
<script lang="ts">
  // No props needed
</script>

<footer style="border-top: 1px solid var(--pob-border); padding: 2rem 0;">
  <div style="max-width: 72rem; margin: 0 auto; padding: 0 1rem;">
    <div style="text-align: center;">
      <p style="font-size: 0.875rem; color: var(--pob-text-muted); margin-bottom: 1rem;">
        Join the Syscoin community
      </p>
      <div style="display: flex; align-items: center; justify-content: center; gap: 2rem; flex-wrap: wrap;">
        <a
          href="https://x.com/syscoin"
          target="_blank"
          rel="noopener noreferrer"
          class="footer-link"
        >
          X (Twitter)
        </a>
        <a
          href="https://discord.com/invite/syscoin"
          target="_blank"
          rel="noopener noreferrer"
          class="footer-link"
        >
          Discord
        </a>
        <a
          href="https://t.me/syscoin_hispano"
          target="_blank"
          rel="noopener noreferrer"
          class="footer-link"
        >
          Telegram (Hispano)
        </a>
      </div>
    </div>
  </div>
</footer>

<style>
  .footer-link {
    font-size: 0.875rem;
    color: var(--pob-primary);
    text-decoration: none;
  }

  .footer-link:hover {
    text-decoration: underline;
  }
</style>

// frontend/src/components/Footer.tsx
const Footer = () => {
  return (
    <footer style={{ borderTop: '1px solid var(--pob-border)', padding: '2rem 0' }}>
      <div style={{ maxWidth: '72rem', margin: '0 auto', padding: '0 1rem' }}>
        <div style={{ textAlign: 'center' }}>
          <p style={{ fontSize: '0.875rem', color: 'var(--pob-text-muted)', marginBottom: '1rem' }}>
            Join the Syscoin community
          </p>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '2rem', flexWrap: 'wrap' }}>
            <a
              href="https://x.com/syscoin"
              target="_blank"
              rel="noopener noreferrer"
              style={{ fontSize: '0.875rem', color: 'var(--pob-primary)', textDecoration: 'none' }}
              onMouseEnter={(e) => (e.currentTarget.style.textDecoration = 'underline')}
              onMouseLeave={(e) => (e.currentTarget.style.textDecoration = 'none')}
            >
              X (Twitter)
            </a>
            <a
              href="https://discord.com/invite/syscoin"
              target="_blank"
              rel="noopener noreferrer"
              style={{ fontSize: '0.875rem', color: 'var(--pob-primary)', textDecoration: 'none' }}
              onMouseEnter={(e) => (e.currentTarget.style.textDecoration = 'underline')}
              onMouseLeave={(e) => (e.currentTarget.style.textDecoration = 'none')}
            >
              Discord
            </a>
            <a
              href="https://t.me/syscoin_hispano"
              target="_blank"
              rel="noopener noreferrer"
              style={{ fontSize: '0.875rem', color: 'var(--pob-primary)', textDecoration: 'none' }}
              onMouseEnter={(e) => (e.currentTarget.style.textDecoration = 'underline')}
              onMouseLeave={(e) => (e.currentTarget.style.textDecoration = 'none')}
            >
              Telegram (Hispano)
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
