// frontend/src/components/IterationHeader.tsx
import { useEffect, useState } from 'react';
import type { Iteration, ParticipantRole, Badge, IterationMetadata } from '~/interfaces';
import { formatDate } from '~/utils';
import { NETWORKS } from '~/constants/networks';
import FinalResultsPanel from './FinalResultsPanel';
import ContractAddress from './ContractAddress';
import MarkdownRenderer from './MarkdownRenderer';
import { Link } from 'react-router-dom';
import { metadataAPI } from '~/utils/metadata-api';

interface CommunityBadge {
  tokenId: string;
  hasVoted: boolean;
  vote: string | null;
  claimed?: boolean;
}

interface RoleStatuses {
  community: boolean;
  devrel: boolean;
  dao_hic: boolean;
  project: boolean;
}

interface IterationHeaderProps {
  iteration: Iteration | null;
  statusBadge: { label: string; color: string };
  iterationTimes: { startTime: number | null; endTime: number | null };
  isActive?: boolean;
  votingEnded?: boolean;
  projectsLocked?: boolean;
  winner?: { projectAddress: string | null; hasWinner: boolean };
  entityVotes?: { devRel: string | null; daoHic: string | null; community: string | null };
  getProjectLabel?: (address: string | null) => string | null;
  isOwner?: boolean;
  walletAddress?: string | null;
  chainId?: number | null;
  pendingAction?: string | null;
  roles?: RoleStatuses;
  badges?: Badge[];
  communityBadges?: CommunityBadge[];
  executeMint?: (role: ParticipantRole, refreshCallback?: () => Promise<void>) => Promise<void>;
  refreshBadges?: () => Promise<void>;
  votingMode?: number;
  projects?: { id: number; address: string; metadata?: any }[];
  projectScores?: { addresses: string[]; scores: string[]; totalPossible: string } | null;
}

const IterationHeader = ({
  iteration,
  statusBadge,
  iterationTimes,
  isActive = false,
  votingEnded,
  projectsLocked,
  winner,
  entityVotes,
  getProjectLabel,
  isOwner = false,
  walletAddress,
  pendingAction,
  roles,
  badges,
  communityBadges,
  executeMint,
  refreshBadges,
  votingMode = 0,
  projects = [],
  projectScores = null,
}: IterationHeaderProps) => {
  const [metadata, setMetadata] = useState<IterationMetadata | null>(null);

  // Load iteration metadata
  useEffect(() => {
    if (!iteration) return;

    const loadMetadata = async () => {
      try {
        const data = await metadataAPI.getIterationMetadata(
          iteration.chainId,
          iteration.jurySC
        );
        setMetadata(data);
      } catch (error) {
        console.error('Failed to load iteration metadata:', error);
      }
    };

    loadMetadata();
  }, [iteration?.chainId, iteration?.jurySC]);

  if (!iteration) {
    return (
      <section className="pob-pane">
        <div>
          <p className="pob-pane__title text-xl">Select a program iteration to get started</p>
        </div>
      </section>
    );
  }

  const network = NETWORKS[iteration.chainId];
  const mintAmount = network?.mintAmount ?? '30';
  const tokenSymbol = network?.tokenSymbol ?? 'TSYS';

  return (
    <section className="pob-pane">
      <div className="pob-pane__heading">
        <div>
          <p className="pob-pane__meta">Current iteration</p>
          <h2 className="pob-pane__title text-3xl">{metadata?.name || iteration.name}</h2>
          <p className="mt-1 text-sm text-[var(--pob-text-muted)]">
            Iteration #{iteration.iteration}{iteration.round ? ` - Round #${iteration.round}` : ''}
            {votingEnded ? (
              winner?.hasWinner ? (
                <span className="pob-pill pob-pill--success text-xs">
                  {votingMode === 0 ? 'Consensus' : 'Weighted'} ✓
                </span>
              ) : (
                <span className="pob-pill pob-pill--failure text-xs">
                  {votingMode === 0 ? 'Consensus' : 'Weighted'} ✗
                </span>
              )
            ) : (
              <span className="pob-pill pob-pill--neutral text-xs">
                {votingMode === 0 ? 'Consensus' : 'Weighted'}
              </span>
            )}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <span className={statusBadge.color}>{statusBadge.label}</span>
        </div>
      </div>
      <dl className="pob-pane__grid text-sm text-[var(--pob-text-muted)] sm:grid-cols-2">
        {statusBadge.label !== 'Upcoming' && (
          <>
            <div>
              <dt className="pob-label">Start Time</dt>
              <dd>{formatDate(iterationTimes.startTime || undefined)}</dd>
            </div>
            <div>
              <dt className="pob-label">End Time</dt>
              <dd>{formatDate(iterationTimes.endTime || undefined)}</dd>
            </div>
          </>
        )}
        <div>
          <dt className="pob-label">Jury Contract</dt>
          <dd><ContractAddress address={iteration.jurySC} chainId={iteration.chainId} /></dd>
        </div>
        <div>
          <dt className="pob-label">PoB Contract</dt>
          <dd><ContractAddress address={iteration.pob} chainId={iteration.chainId} /></dd>
        </div>
      </dl>

      {/* Iteration description */}
      {metadata?.description && (
        <div className="pob-fieldset" style={{ marginTop: '1rem' }}>
          <MarkdownRenderer content={metadata.description} />
        </div>
      )}

      {/* Program brief (left) and Mint button (right) on same line */}
      {(iteration.link || metadata?.link || isOwner || (walletAddress && executeMint)) && (
        <div className="flex items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            {(metadata?.link || iteration.link) && (
              <a
                href={metadata?.link || iteration.link}
                target="_blank"
                rel="noopener noreferrer"
                className="pob-button pob-button--compact"
              >
                Program brief
              </a>
            )}

            {isOwner && (
              <Link
                to={`/iteration/${iteration.iteration}/details`}
                className="pob-button pob-button--compact pob-button--outline"
              >
                Manage iteration
              </Link>
            )}
          </div>

          {walletAddress && executeMint && !isOwner && (() => {
            // Determine user's role (matching JuryPanel logic)
            const hasDevRelBadge = badges?.some(badge => badge.role === 'devrel') ?? false;
            const hasDaoHicBadge = badges?.some(badge => badge.role === 'dao_hic') ?? false;
            const hasProjectBadge = badges?.some(badge => badge.role === 'project') ?? false;
            const hasCommunityBadge = communityBadges && communityBadges.length > 0;

            // DevRel mint button
            if (roles?.devrel && !hasDevRelBadge && votingEnded) {
              return (
                <button
                  type="button"
                  onClick={() => void executeMint('devrel', refreshBadges)}
                  className="pob-button pob-button--compact"
                  disabled={pendingAction !== null}
                >
                  {pendingAction === 'Mint DevRel Badge' ? 'Minting…' : 'Mint DevRel badge'}
                </button>
              );
            }

            // DAO HIC mint button
            if (roles?.dao_hic && !hasDaoHicBadge && votingEnded) {
              return (
                <button
                  type="button"
                  onClick={() => void executeMint('dao_hic', refreshBadges)}
                  className="pob-button pob-button--compact"
                  disabled={pendingAction !== null}
                >
                  {pendingAction === 'Mint DAO HIC Badge' ? 'Minting…' : 'Mint DAO HIC badge'}
                </button>
              );
            }

            // Project mint button
            if (roles?.project && !hasProjectBadge && projectsLocked) {
              return (
                <button
                  type="button"
                  onClick={() => void executeMint('project', refreshBadges)}
                  className="pob-button pob-button--compact"
                  disabled={pendingAction !== null}
                >
                  {pendingAction === 'Mint Project Badge' ? 'Minting…' : 'Mint Project badge'}
                </button>
              );
            }

            // Community mint button - anyone without devrel/dao_hic/project role
            const canBecomeCommunity = !roles?.project && !roles?.devrel && !roles?.dao_hic;
            if (canBecomeCommunity && !hasCommunityBadge && isActive) {
              return (
                <button
                  type="button"
                  onClick={() => void executeMint('community', refreshBadges)}
                  className="pob-button pob-button--compact"
                  disabled={pendingAction !== null}
                >
                  {pendingAction === 'Mint Community Badge' ? 'Minting…' : `Mint community badge (${mintAmount} ${tokenSymbol})`}
                </button>
              );
            }

            return null;
          })()}
        </div>
      )}

      {/* Winner Section - Only show when voting has ended */}
      {votingEnded && winner && entityVotes ? (
        <FinalResultsPanel
          winner={winner}
          entityVotes={entityVotes}
          votingMode={votingMode}
          projects={projects}
          projectScores={projectScores}
          getProjectLabel={getProjectLabel}
          isOwner={isOwner}
        />
      ) : null}
    </section>
  );
};

export default IterationHeader;

// frontend/src/components/IterationHeader.svelte
<script lang="ts">
  import type { Iteration, ParticipantRole, Badge, IterationMetadata } from '~/interfaces';
  import { formatDate } from '~/utils';
  import { NETWORKS } from '~/constants/networks';
  import FinalResultsPanel from './FinalResultsPanel.svelte';
  import ContractAddress from './ContractAddress.svelte';
  import MarkdownRenderer from './MarkdownRenderer.svelte';
  import { Link } from 'svelte-routing';
  import { metadataAPI } from '~/utils/metadata-api';

  interface CommunityBadge {
    tokenId: string;
    hasVoted: boolean;
    vote: string | null;
    claimed?: boolean;
  }

  interface RoleStatuses {
    community: boolean;
    devrel: boolean;
    dao_hic: boolean;
    project: boolean;
  }

  interface Props {
    iteration: Iteration | null;
    statusBadge: { label: string; color: string };
    iterationTimes: { startTime: number | null; endTime: number | null };
    isActive?: boolean;
    votingEnded?: boolean;
    projectsLocked?: boolean;
    winner?: { projectAddress: string | null; hasWinner: boolean };
    entityVotes?: { devRel: string | null; daoHic: string | null; community: string | null };
    daoHicIndividualVotes?: Record<string, string>;
    getProjectLabel?: (address: string | null) => string | null;
    isOwner?: boolean;
    walletAddress?: string | null;
    chainId?: number | null;
    pendingAction?: string | null;
    roles?: RoleStatuses;
    rolesLoading?: boolean;
    badges?: Badge[];
    communityBadges?: CommunityBadge[];
    executeMint?: (role: ParticipantRole, refreshCallback?: () => Promise<void>) => Promise<void>;
    refreshBadges?: () => Promise<void>;
    votingMode?: number;
    projects?: { id: number; address: string; metadata?: any }[];
    projectScores?: { addresses: string[]; scores: string[]; totalPossible: string } | null;
  }

  let {
    iteration,
    statusBadge,
    iterationTimes,
    isActive = false,
    votingEnded,
    projectsLocked,
    winner,
    entityVotes,
    daoHicIndividualVotes,
    getProjectLabel,
    isOwner = false,
    walletAddress,
    pendingAction,
    roles,
    rolesLoading = false,
    badges,
    communityBadges,
    executeMint,
    refreshBadges,
    votingMode = 0,
    projects = [],
    projectScores = null,
  }: Props = $props();

  let metadata = $state<IterationMetadata | null>(null);

  // Load iteration metadata
  $effect(() => {
    if (!iteration) return;

    const loadMetadata = async () => {
      try {
        const data = await metadataAPI.getIterationMetadata(
          iteration!.chainId,
          iteration!.jurySC
        );
        metadata = data;
      } catch (error) {
        console.error('Failed to load iteration metadata:', error);
      }
    };

    loadMetadata();
  });

  let network = $derived(iteration ? NETWORKS[iteration.chainId] : null);
  let mintAmount = $derived(network?.mintAmount ?? '30');
  let tokenSymbol = $derived(network?.tokenSymbol ?? 'TSYS');

  // Determine user's role and mint button visibility
  let hasDevRelBadge = $derived(badges?.some(badge => badge.role === 'devrel') ?? false);
  let hasDaoHicBadge = $derived(badges?.some(badge => badge.role === 'dao_hic') ?? false);
  let hasProjectBadge = $derived(badges?.some(badge => badge.role === 'project') ?? false);
  let hasCommunityBadge = $derived(communityBadges && communityBadges.length > 0);

  let canBecomeCommunity = $derived(
    !roles?.project && !roles?.devrel && !roles?.dao_hic && !roles?.community
  );

  // Determine which mint button to show
  let mintButtonType = $derived.by((): 'devrel' | 'dao_hic' | 'project' | 'community' | null => {
    if (!walletAddress || !executeMint || isOwner) return null;

    if (roles?.devrel && !hasDevRelBadge && votingEnded) return 'devrel';
    if (roles?.dao_hic && !hasDaoHicBadge && votingEnded) return 'dao_hic';
    if (roles?.project && !hasProjectBadge && projectsLocked) return 'project';
    if (rolesLoading) return null;
    if (canBecomeCommunity && !hasCommunityBadge && isActive) return 'community';

    return null;
  });

  // Show the action row?
  let showActionRow = $derived(
    iteration && (iteration.link || metadata?.link || isOwner || (walletAddress && executeMint))
  );

  function handleMint() {
    if (!executeMint || !mintButtonType) return;
    void executeMint(mintButtonType, refreshBadges);
  }
</script>

{#if !iteration}
  <section class="pob-pane">
    <div>
      <p class="pob-pane__title text-xl">Select a program iteration to get started</p>
    </div>
  </section>
{:else}
  <section class="pob-pane">
    <div class="pob-pane__heading">
      <div>
        <p class="pob-pane__meta">Current iteration</p>
        <h2 class="pob-pane__title text-3xl">{metadata?.name || iteration.name}</h2>
        <p class="mt-1 text-sm text-[var(--pob-text-muted)]">
          Iteration #{iteration.iteration}{iteration.round ? ` - Round #${iteration.round}` : ''}
          {#if votingEnded}
            {#if winner?.hasWinner}
              <span class="pob-pill pob-pill--success text-xs">
                {votingMode === 0 ? 'Consensus' : 'Weighted'} ✓
              </span>
            {:else}
              <span class="pob-pill pob-pill--failure text-xs">
                {votingMode === 0 ? 'Consensus' : 'Weighted'} ✗
              </span>
            {/if}
          {:else}
            <span class="pob-pill pob-pill--neutral text-xs">
              {votingMode === 0 ? 'Consensus' : 'Weighted'}
            </span>
          {/if}
        </p>
      </div>
      <div class="flex items-center gap-2">
        <span class={statusBadge.color}>{statusBadge.label}</span>
      </div>
    </div>
    <dl class="pob-pane__grid text-sm text-[var(--pob-text-muted)] sm:grid-cols-2">
      {#if statusBadge.label !== 'Upcoming'}
        <div>
          <dt class="pob-label">Start Time</dt>
          <dd>{formatDate(iterationTimes.startTime || undefined)}</dd>
        </div>
        <div>
          <dt class="pob-label">End Time</dt>
          <dd>{formatDate(iterationTimes.endTime || undefined)}</dd>
        </div>
      {/if}
      <div>
        <dt class="pob-label">Jury Contract</dt>
        <dd><ContractAddress address={iteration.jurySC} chainId={iteration.chainId} /></dd>
      </div>
      <div>
        <dt class="pob-label">PoB Contract</dt>
        <dd><ContractAddress address={iteration.pob} chainId={iteration.chainId} /></dd>
      </div>
    </dl>

    <!-- Iteration description -->
    {#if metadata?.description}
      <div class="pob-fieldset" style="margin-top: 1rem;">
        <MarkdownRenderer content={metadata.description} />
      </div>
    {/if}

    <!-- Program brief (left) and Mint button (right) on same line -->
    {#if showActionRow}
      <div class="flex items-center justify-between gap-2">
        <div class="flex items-center gap-2">
          {#if metadata?.link || iteration.link}
            <a
              href={metadata?.link || iteration.link}
              target="_blank"
              rel="noopener noreferrer"
              class="pob-button pob-button--compact"
            >
              Program brief
            </a>
          {/if}

          {#if isOwner}
            <Link
              to="/iteration/{iteration.iteration}/details"
              class="pob-button pob-button--compact pob-button--outline"
            >
              Manage iteration
            </Link>
          {/if}
        </div>

        {#if mintButtonType === 'devrel'}
          <button
            type="button"
            onclick={handleMint}
            class="pob-button pob-button--compact"
            disabled={pendingAction !== null}
          >
            {pendingAction === 'Mint DevRel Badge' ? 'Minting...' : 'Mint DevRel badge'}
          </button>
        {:else if mintButtonType === 'dao_hic'}
          <button
            type="button"
            onclick={handleMint}
            class="pob-button pob-button--compact"
            disabled={pendingAction !== null}
          >
            {pendingAction === 'Mint DAO HIC Badge' ? 'Minting...' : 'Mint DAO HIC badge'}
          </button>
        {:else if mintButtonType === 'project'}
          <button
            type="button"
            onclick={handleMint}
            class="pob-button pob-button--compact"
            disabled={pendingAction !== null}
          >
            {pendingAction === 'Mint Project Badge' ? 'Minting...' : 'Mint Project badge'}
          </button>
        {:else if mintButtonType === 'community'}
          <button
            type="button"
            onclick={handleMint}
            class="pob-button pob-button--compact"
            disabled={pendingAction !== null}
          >
            {pendingAction === 'Mint Community Badge' ? 'Minting...' : `Mint community badge (${mintAmount} ${tokenSymbol})`}
          </button>
        {/if}
      </div>
    {/if}

    <!-- Winner Section - Only show when voting has ended -->
    {#if votingEnded && winner && entityVotes}
      <FinalResultsPanel
        {winner}
        {entityVotes}
        {daoHicIndividualVotes}
        {votingMode}
        {projects}
        {projectScores}
        {getProjectLabel}
        {isOwner}
        iterationNumber={iteration?.iteration}
      />
    {/if}
  </section>
{/if}
