// frontend/src/pages/ProjectPage.tsx
import { useMemo, useCallback, useState, useEffect, useRef } from 'react';
import { useParams, Link } from 'react-router-dom';
import type { Iteration, ParticipantRole, Project, Badge } from '~/interfaces';
import type { JsonRpcSigner } from 'ethers';
import MarkdownRenderer from '~/components/MarkdownRenderer';
import VoteConfirmationModal from '~/components/VoteConfirmationModal';
import { formatAddress, getYouTubeEmbedUrl, getExplorerTxLink, getMetadataCidUrl } from '~/utils';
import { NETWORKS } from '~/constants/networks';
import { ROLE_LABELS, ROLE_COLORS } from '~/constants/roles';
import { useRegistryStatus } from '~/hooks/useRegistryStatus';
import { useProjectMetadataManager } from '~/hooks/useProjectMetadataManager';
import { ProgressSpinner } from '~/components/ProgressSpinner';

interface CommunityBadge {
  tokenId: string;
  hasVoted: boolean;
  vote: string | null;
  claimed?: boolean;
  iteration: number;
  round?: number;
}

interface RoleStatuses {
  community: boolean;
  devrel: boolean;
  dao_hic: boolean;
  project: boolean;
}

interface StatusFlags {
  isActive: boolean;
  votingEnded: boolean;
}

interface ProjectPageProps {
  currentIteration: Iteration | null;
  projects: Project[];
  loading: boolean;
  roles: RoleStatuses;
  isOwner: boolean;
  projectsLocked: boolean;
  statusFlags: StatusFlags;
  communityBadges: CommunityBadge[];
  badges: Badge[];
  devRelVote: string | null;
  daoHicVote: string | null;
  pendingAction: string | null;
  walletAddress: string | null;
  chainId: number | null;
  signer: JsonRpcSigner | null;
  getProjectLabel: (address: string | null) => string | null;
  executeMint: (role: ParticipantRole, refreshCallback?: () => Promise<void>) => Promise<void>;
  executeVote: (role: ParticipantRole, projectAddress: string, tokenId?: string, refreshCallback?: () => Promise<void>) => void;
  refreshVotingData: () => Promise<void>;
  refreshBadges: () => Promise<void>;
}

const ProjectPage = ({
  currentIteration,
  projects,
  loading,
  roles,
  isOwner,
  projectsLocked,
  statusFlags,
  communityBadges,
  badges,
  devRelVote,
  daoHicVote,
  pendingAction,
  walletAddress,
  chainId,
  signer,
  getProjectLabel,
  executeMint,
  executeVote,
  refreshVotingData,
  refreshBadges,
}: ProjectPageProps) => {
  const { projectAddress } = useParams<{ projectAddress: string }>();
  const [sidebarVisible, setSidebarVisible] = useState(window.innerWidth >= 1024);
  const wasLargeScreen = useRef(window.innerWidth >= 1024);

  // Find the project - check current round first, then previous rounds
  const project = useMemo(() => {
    if (!projectAddress) return null;
    const addrLower = projectAddress.toLowerCase();

    // Check current round projects
    const currentRoundProject = projects.find(p => p.address.toLowerCase() === addrLower);
    if (currentRoundProject) return currentRoundProject;

    // Check previous rounds if not found
    if (currentIteration?.prev_rounds) {
      for (const round of currentIteration.prev_rounds) {
        if (round.projects) {
          const prevProject = round.projects.find(p => p.address.toLowerCase() === addrLower);
          if (prevProject) {
            // Convert to Project interface
            return {
              id: 0, // ID not meaningful for previous round projects
              address: prevProject.address,
              metadata: prevProject.metadata as unknown as Project['metadata'],
            };
          }
        }
      }
    }

    return null;
  }, [projects, projectAddress, currentIteration]);

  // Use iteration's chainId for registry status (not wallet's chainId)
  const iterationChainId = currentIteration?.chainId ?? null;
  const contractAddress = currentIteration?.jurySC ?? null;
  const { registryAvailable, initializationComplete, registryOwner } = useRegistryStatus(iterationChainId);

  // Project metadata manager - for status display
  const {
    currentCID,
    currentTxHash,
    pendingCID,
    pendingTxHash,
    pendingConfirmations,
  } = useProjectMetadataManager(
    project?.address || null,
    iterationChainId,
    contractAddress,
    signer,
    projectsLocked
  );

  // Auto-hide sidebar below 1024px breakpoint
  useEffect(() => {
    const handleResize = () => {
      const isLargeScreen = window.innerWidth >= 1024;
      if (wasLargeScreen.current !== isLargeScreen) {
        wasLargeScreen.current = isLargeScreen;
        setSidebarVisible(isLargeScreen);
      }
    };
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Filter badges to only those for the current iteration and round
  const currentIterationBadges = useMemo(
    () => badges.filter((badge) =>
      badge.iteration === currentIteration?.iteration &&
      badge.round === currentIteration?.round
    ),
    [badges, currentIteration],
  );

  const currentIterationCommunityBadges = useMemo(
    () => communityBadges.filter((badge) =>
      badge.iteration === currentIteration?.iteration &&
      badge.round === currentIteration?.round
    ),
    [communityBadges, currentIteration],
  );

  // Determine voting role
  const votingRole: ParticipantRole | null = useMemo(() => {
    if (!walletAddress) return null;
    if (isOwner) return null;
    if (roles.project) return null;
    if (roles.devrel) return 'devrel';
    if (roles.dao_hic) return 'dao_hic';
    return 'community';
  }, [walletAddress, isOwner, roles]);

  // Check if user has voted for this project
  const hasVotedForThisProject = useMemo(() => {
    if (!project) return false;
    if (votingRole === 'devrel') {
      return devRelVote?.toLowerCase() === project.address.toLowerCase();
    }
    if (votingRole === 'dao_hic') {
      return daoHicVote?.toLowerCase() === project.address.toLowerCase();
    }
    if (votingRole === 'community') {
      return currentIterationCommunityBadges.some(
        b => b.hasVoted && b.vote?.toLowerCase() === project.address.toLowerCase()
      );
    }
    return false;
  }, [project, votingRole, devRelVote, daoHicVote, currentIterationCommunityBadges]);

  // Check if user has voted anywhere
  const hasVotedAnywhere = useMemo(() => {
    if (votingRole === 'devrel') return devRelVote !== null;
    if (votingRole === 'dao_hic') return daoHicVote !== null;
    if (votingRole === 'community') return currentIterationCommunityBadges.some(b => b.hasVoted);
    return false;
  }, [votingRole, devRelVote, daoHicVote, currentIterationCommunityBadges]);

  // Can vote (can always change vote during active voting)
  const canVote = votingRole !== null &&
                  statusFlags.isActive &&
                  !statusFlags.votingEnded;

  // Vote modal state
  const [showVoteModal, setShowVoteModal] = useState(false);

  // Handle vote button click - opens confirmation modal
  const handleVoteClick = useCallback(() => {
    if (!votingRole || !project) return;
    setShowVoteModal(true);
  }, [votingRole, project]);

  // Handle confirmed vote from modal
  const handleConfirmVote = useCallback(async () => {
    if (!votingRole || !project) return;
    const tokenId = votingRole === 'community' ? currentIterationCommunityBadges[0]?.tokenId : undefined;
    await executeVote(votingRole, project.address, tokenId, refreshVotingData);
    setShowVoteModal(false);
  }, [votingRole, project, currentIterationCommunityBadges, executeVote, refreshVotingData]);

  // Legacy handleVote for DevRel/DAO HIC (they don't need mint flow)
  const handleVote = useCallback(async () => {
    if (!votingRole || !project) return;
    const tokenId = votingRole === 'community' ? currentIterationCommunityBadges[0]?.tokenId : undefined;
    await executeVote(votingRole, project.address, tokenId, refreshVotingData);
  }, [votingRole, project, currentIterationCommunityBadges, executeVote, refreshVotingData]);

  // Get network-specific values
  const network = chainId ? NETWORKS[chainId] : null;
  const mintAmount = network?.mintAmount ?? '30';
  const tokenSymbol = network?.tokenSymbol ?? 'TSYS';

  // Determine header role tag
  const headerRoleTag = roles.devrel
    ? { label: ROLE_LABELS.devrel, color: ROLE_COLORS.devrel }
    : roles.dao_hic
    ? { label: ROLE_LABELS.dao_hic, color: ROLE_COLORS.dao_hic }
    : (roles.community || (!roles.project && !isOwner))
    ? { label: ROLE_LABELS.community, color: ROLE_COLORS.community }
    : null;

  const hasJuryRole = roles.devrel || roles.dao_hic || roles.community;
  const canBecomeCommunity = !roles.project && !roles.devrel && !roles.dao_hic && !roles.community && !isOwner;
  const hasDevRelBadge = currentIterationBadges?.some(badge => badge.role === 'devrel') ?? false;
  const hasDaoHicBadge = currentIterationBadges?.some(badge => badge.role === 'dao_hic') ?? false;
  const canEditMetadata = useMemo(() => {
    if (!project || !walletAddress) return false;
    if (!registryAvailable || initializationComplete === null) return false;

    const walletLower = walletAddress.toLowerCase();

    // Owner bypass: when VITE_OWNER_METADATA_BYPASS is enabled, registry owner can edit any project
    const ownerBypassEnabled = import.meta.env.VITE_OWNER_METADATA_BYPASS === 'true';
    const isRegistryOwner = Boolean(registryOwner && walletLower === registryOwner.toLowerCase());

    if (ownerBypassEnabled && isRegistryOwner) {
      return true;
    }

    if (!initializationComplete) {
      return isRegistryOwner;
    }

    if (projectsLocked) return false;
    return walletLower === project.address.toLowerCase();
  }, [project, walletAddress, registryAvailable, initializationComplete, registryOwner, projectsLocked]);

  // Can see metadata status section: registry owner or project wallet
  const canSeeMetadataStatus = useMemo(() => {
    if (!project || !walletAddress) return false;
    const walletLower = walletAddress.toLowerCase();
    const isRegistryOwner = Boolean(registryOwner && walletLower === registryOwner.toLowerCase());
    const isProjectWallet = walletLower === project.address.toLowerCase();
    return isRegistryOwner || isProjectWallet;
  }, [project, walletAddress, registryOwner]);

  if (loading) {
    return (
      <div className="pob-stack">
        <p className="text-sm text-[var(--pob-text-muted)]">Loading project...</p>
      </div>
    );
  }

  if (!project) {
    return (
      <div className="pob-stack">
        <section className="pob-pane">
          <p className="text-sm text-[var(--pob-text-muted)]">Project not found.</p>
          <Link
            to={`/iteration/${currentIteration?.iteration ?? 1}`}
            className="pob-button pob-button--outline pob-button--compact"
            style={{ marginTop: '1rem', display: 'inline-flex' }}
          >
            Back to Iteration
          </Link>
        </section>
      </div>
    );
  }

  const projectName = project.metadata?.name ?? `Project #${project.id}`;
  const embedUrl = getYouTubeEmbedUrl(project.metadata?.yt_vid ?? null);

  return (
    <>
      {/* Main content */}
      <div className="pob-stack lg:pr-4" style={!sidebarVisible ? { gridColumn: '1 / -1' } : {}}>
        {/* Back link */}
        <Link
          to={`/iteration/${currentIteration?.iteration ?? 1}`}
          className="text-sm text-[var(--pob-text-muted)] hover:text-[var(--pob-primary)]"
          style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem' }}
        >
          ← Back to Projects
        </Link>

        {/* Project card without vote button */}
        <section className="pob-pane">
          <div className="space-y-4">
            <div className="pob-pane__heading project-page__heading">
              <div>
                <h1 className="project-page__title">{projectName}</h1>
                <p className="pob-mono text-xs text-[var(--pob-text-muted)]">
                  {formatAddress(project.address)}
                </p>
              </div>
              {canEditMetadata && (
                <Link
                  to={`/iteration/${currentIteration?.iteration}/project/${project.address}/edit`}
                  className="pob-button pob-button--outline pob-button--compact project-page__edit"
                >
                  Edit
                </Link>
              )}
            </div>

            {/* Full description */}
            <div className="project-page__description">
              <MarkdownRenderer content={project.metadata?.description} />
            </div>

            {/* Video embed */}
            {embedUrl ? (
              <div className="pob-video" style={{ marginTop: '1.5rem', marginBottom: '1rem' }}>
                <iframe
                  src={embedUrl}
                  title={`Project video for ${projectName}`}
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                  allowFullScreen
                />
              </div>
            ) : null}

            {/* Proposal link */}
            {project.metadata?.proposal ? (
              <div style={{ marginTop: '1rem' }}>
                <a
                  href={project.metadata.proposal}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="pob-button pob-button--outline pob-button--compact"
                >
                  Read full proposal
                </a>
              </div>
            ) : null}

            {/* Social links + on-chain metadata links */}
            <div className="pob-socials" style={{ marginTop: '1.5rem' }}>
              {/* Social links on the left */}
              {project.metadata?.socials?.x && (
                <a
                  href={project.metadata.socials.x}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="pob-socials__link pob-socials__link--x"
                  title="X (Twitter)"
                >
                  X
                </a>
              )}
              {project.metadata?.socials?.instagram && (
                <a
                  href={project.metadata.socials.instagram}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="pob-socials__link"
                  title="Instagram"
                >
                  Instagram
                </a>
              )}
              {project.metadata?.socials?.tiktok && (
                <a
                  href={project.metadata.socials.tiktok}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="pob-socials__link"
                  title="TikTok"
                >
                  TikTok
                </a>
              )}
              {project.metadata?.socials?.linkedin && (
                <a
                  href={project.metadata.socials.linkedin}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="pob-socials__link"
                  title="LinkedIn"
                >
                  LinkedIn
                </a>
              )}

              {/* Spacer to push on-chain links to the right */}
              <span style={{ flex: 1 }} />

              {/* On-chain metadata links on the right */}
              {currentCID && (
                <a
                  href={getMetadataCidUrl(currentCID)}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="pob-socials__link"
                  title={`IPFS CID: ${currentCID}`}
                >
                  📦 IPFS
                </a>
              )}
              {currentTxHash && iterationChainId && (
                <a
                  href={getExplorerTxLink(iterationChainId, currentTxHash)}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="pob-socials__link"
                  title={`Transaction: ${currentTxHash}`}
                >
                  ⛓️ TX
                </a>
              )}
            </div>

            {/* Metadata Status Section - visible to owner/project wallet only */}
            {canSeeMetadataStatus && pendingCID && (
              <>
                {!currentCID && <div className="pob-pane__divider" />}
                <div className="pob-stack--dense" style={{ marginTop: currentCID ? '0.75rem' : undefined }}>
                  <p className="pob-pane__meta">Update Status</p>
                  <div className="flex items-center gap-3 text-xs">
                    <a
                      href={getMetadataCidUrl(pendingCID)}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-[var(--pob-primary)] hover:underline"
                      title={`Pending CID: ${pendingCID}`}
                    >
                      📦 IPFS
                    </a>
                    {pendingTxHash && iterationChainId && (
                      <a
                        href={getExplorerTxLink(iterationChainId, pendingTxHash)}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-[var(--pob-primary)] hover:underline"
                        title={`Transaction: ${pendingTxHash}`}
                      >
                        🔗 TX
                      </a>
                    )}
                    <span className="pob-pill flex items-center gap-1">
                      <ProgressSpinner size={16} progress={Math.min((pendingConfirmations / 5) * 100, 100)} />
                      {pendingConfirmations}/5
                    </span>
                  </div>
                </div>
              </>
            )}

          </div>
        </section>
      </div>

      {/* Sidebar with voting panel */}
      {sidebarVisible && (
        <div className="pob-stack lg:pl-4">
          {/* Jury Panel - Vote for this specific project */}
          {(hasJuryRole || canBecomeCommunity) && !isOwner && (
            <section className="pob-pane">
              <div className="pob-pane__heading">
                <h3 className="pob-pane__title">Jury Panel</h3>
                {headerRoleTag && (
                  <span className={`pob-pill ${headerRoleTag.color}`}>
                    {headerRoleTag.label}
                  </span>
                )}
              </div>

              <div className="space-y-3">
                {/* DevRel Role */}
                {roles.devrel && (
                  <>
                    <p className="text-sm text-[var(--pob-text-muted)]">
                      As DevRel, cast your vote for <span className="font-semibold text-white">{projectName}</span>.
                    </p>
                    {devRelVote && (
                      <p className="text-sm text-[var(--pob-text-muted)]">
                        Currently voted for{' '}
                        <span className="italic">
                          {getProjectLabel(devRelVote) ?? 'Unknown project'}
                        </span>
                      </p>
                    )}
                    {canVote && (
                      <button
                        type="button"
                        onClick={handleVote}
                        disabled={pendingAction !== null}
                        className="pob-button w-full justify-center"
                      >
                        {hasVotedForThisProject ? 'Voted' : hasVotedAnywhere ? 'Change Vote' : 'Vote'}
                      </button>
                    )}
                    {!hasDevRelBadge && statusFlags.votingEnded && (
                      <button
                        type="button"
                        onClick={() => void executeMint('devrel', refreshBadges)}
                        className="pob-button pob-button--outline w-full justify-center text-xs"
                        disabled={pendingAction !== null || !walletAddress}
                      >
                        Mint DevRel badge
                      </button>
                    )}
                  </>
                )}

                {/* DAO HIC Role */}
                {roles.dao_hic && (
                  <>
                    <p className="text-sm text-[var(--pob-text-muted)]">
                      As a DAO HIC voter, cast your vote for <span className="font-semibold text-white">{projectName}</span>.
                    </p>
                    {daoHicVote && (
                      <p className="text-sm text-[var(--pob-text-muted)]">
                        Currently voted for{' '}
                        <span className="italic">
                          {getProjectLabel(daoHicVote) ?? 'Unknown project'}
                        </span>
                      </p>
                    )}
                    {canVote && (
                      <button
                        type="button"
                        onClick={handleVote}
                        disabled={pendingAction !== null}
                        className="pob-button w-full justify-center"
                      >
                        {hasVotedForThisProject ? 'Voted' : hasVotedAnywhere ? 'Change Vote' : 'Vote'}
                      </button>
                    )}
                    {!hasDaoHicBadge && statusFlags.votingEnded && (
                      <button
                        type="button"
                        onClick={() => void executeMint('dao_hic', refreshBadges)}
                        className="pob-button pob-button--outline w-full justify-center text-xs"
                        disabled={pendingAction !== null || !walletAddress}
                      >
                        Mint DAO HIC badge
                      </button>
                    )}
                  </>
                )}

                {/* Community Role */}
                {(roles.community || canBecomeCommunity) && (
                  <>
                    <p className="text-sm text-[var(--pob-text-muted)]">
                      {hasVotedAnywhere ? (
                        <>
                          Currently voted for{' '}
                          <span className="italic">
                            {getProjectLabel(currentIterationCommunityBadges.find(b => b.hasVoted)?.vote ?? null) ?? 'Unknown'}
                          </span>
                        </>
                      ) : (
                        <>Vote for <span className="font-semibold text-white">{projectName}</span>.</>
                      )}
                    </p>
                    {statusFlags.isActive && !statusFlags.votingEnded && walletAddress && (
                      <button
                        type="button"
                        onClick={handleVoteClick}
                        disabled={pendingAction !== null}
                        className="pob-button w-full justify-center"
                      >
                        {hasVotedForThisProject ? 'Voted' : hasVotedAnywhere ? 'Change Vote' : 'Vote'}
                      </button>
                    )}
                    {statusFlags.isActive && (
                      <p className="text-xs text-[var(--pob-text-muted)] italic">
                        You can change your vote at any time during the voting period.
                      </p>
                    )}
                  </>
                )}

                {/* Voting ended message */}
                {statusFlags.votingEnded && (
                  <p className="text-xs text-[var(--pob-text-muted)] italic">
                    Voting has ended for this iteration.
                  </p>
                )}

                {/* Not active yet */}
                {!statusFlags.isActive && !statusFlags.votingEnded && (
                  <p className="text-xs text-[var(--pob-text-muted)] italic">
                    Voting has not started yet.
                  </p>
                )}
              </div>
            </section>
          )}

          {/* Owner message */}
          {isOwner && (
            <section className="pob-pane">
              <div className="pob-pane__heading">
                <h3 className="pob-pane__title">Owner View</h3>
              </div>
              <p className="text-sm text-[var(--pob-text-muted)]">
                As the contract owner, you cannot vote on projects.
              </p>
            </section>
          )}

          {/* Project participant message */}
          {roles.project && !isOwner && (
            <section className="pob-pane">
              <div className="pob-pane__heading">
                <h3 className="pob-pane__title">Participant View</h3>
              </div>
              <p className="text-sm text-[var(--pob-text-muted)]">
                As a project participant, you cannot vote on projects.
              </p>
            </section>
          )}
        </div>
      )}

      {/* Mobile toggle for sidebar */}
      {!sidebarVisible && (hasJuryRole || canBecomeCommunity) && !isOwner && (
        <button
          type="button"
          onClick={() => setSidebarVisible(true)}
          className="pob-button pob-button--outline"
          style={{ position: 'fixed', bottom: '1rem', right: '1rem', zIndex: 50 }}
        >
          Vote
        </button>
      )}

      {/* Vote Confirmation Modal */}
      {project && showVoteModal && (
        <VoteConfirmationModal
          isOpen={true}
          onClose={() => setShowVoteModal(false)}
          onConfirm={handleConfirmVote}
          projectName={projectName}
          projectAddress={project.address}
          votingRole={votingRole}
          hasVotedForProject={hasVotedForThisProject}
          hasBadge={currentIterationBadges.length > 0}
          executeMint={executeMint}
          refreshBadges={refreshBadges}
          isPending={pendingAction !== null}
          mintAmount={mintAmount}
          tokenSymbol={tokenSymbol}
        />
      )}
    </>
  );
};

export default ProjectPage;

// frontend/src/pages/ProjectPage.svelte
<script lang="ts">
  import { Link, navigate } from 'svelte-routing';
  import { get } from 'svelte/store';
  import type { Iteration, ParticipantRole, Project, Badge, CommunityBadge, RoleStatuses, StatusFlags } from '~/interfaces';
  import type { JsonRpcSigner } from 'ethers';
  import MarkdownRenderer from '~/components/MarkdownRenderer.svelte';
  import VoteConfirmationModal from '~/components/VoteConfirmationModal.svelte';
  import ProgressSpinner from '~/components/ProgressSpinner.svelte';
  import { formatAddress, getYouTubeEmbedUrl, getExplorerTxLink, getMetadataCidUrl } from '~/utils';
  import { NETWORKS } from '~/constants/networks';
  import { ROLE_LABELS, ROLE_COLORS } from '~/constants/roles';
  import { createRegistryStatusStore } from '~/stores/registryStatus';
  import { createProjectMetadataManager } from '~/stores/projectMetadataManager';

  interface Props {
    projectAddress: string;
    currentIteration: Iteration | null;
    projects: Project[];
    loading: boolean;
    roles: RoleStatuses;
    isOwner: boolean;
    projectsLocked: boolean;
    statusFlags: StatusFlags;
    communityBadges: CommunityBadge[];
    badges: Badge[];
    devRelVote: string | null;
    daoHicVote: string | null;
    pendingAction: string | null;
    walletAddress: string | null;
    chainId: number | null;
    signer: JsonRpcSigner | null;
    getProjectLabel: (address: string | null) => string | null;
    executeMint: (role: ParticipantRole, refreshCallback?: () => Promise<void>) => Promise<void>;
    executeVote: (role: ParticipantRole, projectAddress: string, tokenId?: string, refreshCallback?: () => Promise<void>) => void;
    refreshVotingData: () => Promise<void>;
    refreshBadges: () => Promise<void>;
  }

  let {
    projectAddress,
    currentIteration,
    projects,
    loading,
    roles,
    isOwner,
    projectsLocked,
    statusFlags,
    communityBadges,
    badges,
    devRelVote,
    daoHicVote,
    pendingAction,
    walletAddress,
    chainId,
    signer,
    getProjectLabel,
    executeMint,
    executeVote,
    refreshVotingData,
    refreshBadges,
  }: Props = $props();

  let sidebarVisible = $state(typeof window !== 'undefined' ? window.innerWidth >= 1024 : true);
  let showVoteModal = $state(false);

  // Find the project - check current round first, then previous rounds
  const project = $derived.by(() => {
    if (!projectAddress) return null;
    const addrLower = projectAddress.toLowerCase();

    // Check current round projects
    const currentRoundProject = projects.find(p => p.address.toLowerCase() === addrLower);
    if (currentRoundProject) return currentRoundProject;

    // Check previous rounds if not found
    if (currentIteration?.prev_rounds) {
      for (const round of currentIteration.prev_rounds) {
        if (round.projects) {
          const prevProject = round.projects.find(p => p.address.toLowerCase() === addrLower);
          if (prevProject) {
            return {
              id: 0,
              address: prevProject.address,
              metadata: prevProject.metadata as unknown as Project['metadata'],
            };
          }
        }
      }
    }

    return null;
  });

  // Use iteration's chainId for registry status
  const iterationChainId = $derived(currentIteration?.chainId ?? null);
  const contractAddress = $derived(currentIteration?.jurySC ?? null);

  // Registry status store
  let registryStatusManager = $state<ReturnType<typeof createRegistryStatusStore> | null>(null);

  $effect(() => {
    const manager = createRegistryStatusStore(iterationChainId);
    registryStatusManager = manager;
    return () => manager.destroy();
  });

  const registryAvailable = $derived(registryStatusManager?.registryAvailable ?? false);
  const initializationComplete = $derived(
    registryStatusManager?.initializationComplete ? get(registryStatusManager.initializationComplete) : null
  );
  const registryOwner = $derived(
    registryStatusManager?.registryOwner ? get(registryStatusManager.registryOwner) : null
  );

  // Project metadata manager - use $effect for proper lifecycle management
  let metadataManager = $state<ReturnType<typeof createProjectMetadataManager> | null>(null);
  let metadataState = $state<{
    currentCID: string | null;
    currentTxHash: string | null;
    pendingCID: string | null;
    pendingTxHash: string | null;
    pendingConfirmations: number;
  }>({
    currentCID: null,
    currentTxHash: null,
    pendingCID: null,
    pendingTxHash: null,
    pendingConfirmations: 0,
  });

  $effect(() => {
    const addr = project?.address || null;
    const chain = iterationChainId;
    const contract = contractAddress;
    const sig = signer;
    const locked = projectsLocked;

    if (!addr || !chain || !contract) {
      metadataManager = null;
      return;
    }

    const manager = createProjectMetadataManager(addr, chain, contract, sig, locked);
    metadataManager = manager;

    // Subscribe to state changes
    const unsubscribe = manager.subscribe((state) => {
      metadataState = {
        currentCID: state.currentCID,
        currentTxHash: state.currentTxHash,
        pendingCID: state.pendingCID,
        pendingTxHash: state.pendingTxHash,
        pendingConfirmations: state.pendingConfirmations,
      };
    });

    return () => {
      unsubscribe();
      manager.destroy();
    };
  });

  const currentCID = $derived(metadataState.currentCID);
  const currentTxHash = $derived(metadataState.currentTxHash);
  const pendingCID = $derived(metadataState.pendingCID);
  const pendingTxHash = $derived(metadataState.pendingTxHash);
  const pendingConfirmations = $derived(metadataState.pendingConfirmations);

  // Auto-hide sidebar below 1024px breakpoint
  $effect(() => {
    if (typeof window === 'undefined') return;

    let wasLargeScreen = window.innerWidth >= 1024;

    const handleResize = () => {
      const isLargeScreen = window.innerWidth >= 1024;
      if (wasLargeScreen !== isLargeScreen) {
        wasLargeScreen = isLargeScreen;
        sidebarVisible = isLargeScreen;
      }
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  });

  // Filter badges to only those for the current iteration and round
  const currentIterationBadges = $derived(
    badges.filter((badge) =>
      badge.iteration === currentIteration?.iteration &&
      badge.round === currentIteration?.round
    )
  );

  const currentIterationCommunityBadges = $derived(
    communityBadges.filter((badge) =>
      badge.iteration === currentIteration?.iteration &&
      badge.round === currentIteration?.round
    )
  );

  // Determine voting role
  const votingRole: ParticipantRole | null = $derived.by(() => {
    if (!walletAddress) return null;
    if (isOwner) return null;
    if (roles.project) return null;
    if (roles.devrel) return 'devrel';
    if (roles.dao_hic) return 'dao_hic';
    return 'community';
  });

  // Check if user has voted for this project
  const hasVotedForThisProject = $derived.by(() => {
    if (!project) return false;
    if (votingRole === 'devrel') {
      return devRelVote?.toLowerCase() === project.address.toLowerCase();
    }
    if (votingRole === 'dao_hic') {
      return daoHicVote?.toLowerCase() === project.address.toLowerCase();
    }
    if (votingRole === 'community') {
      return currentIterationCommunityBadges.some(
        b => b.hasVoted && b.vote?.toLowerCase() === project.address.toLowerCase()
      );
    }
    return false;
  });

  // Check if user has voted anywhere
  const hasVotedAnywhere = $derived.by(() => {
    if (votingRole === 'devrel') return devRelVote !== null;
    if (votingRole === 'dao_hic') return daoHicVote !== null;
    if (votingRole === 'community') return currentIterationCommunityBadges.some(b => b.hasVoted);
    return false;
  });

  // Can vote (can always change vote during active voting)
  const canVote = $derived(
    votingRole !== null &&
    statusFlags.isActive &&
    !statusFlags.votingEnded
  );

  // Handle vote button click - opens confirmation modal
  function handleVoteClick() {
    if (!votingRole || !project) return;
    showVoteModal = true;
  }

  // Handle confirmed vote from modal
  async function handleConfirmVote() {
    if (!votingRole || !project) return;
    const tokenId = votingRole === 'community' ? currentIterationCommunityBadges[0]?.tokenId : undefined;
    await executeVote(votingRole, project.address, tokenId, refreshVotingData);
    showVoteModal = false;
  }

  // Legacy handleVote for DevRel/DAO HIC (they don't need mint flow)
  async function handleVote() {
    if (!votingRole || !project) return;
    const tokenId = votingRole === 'community' ? currentIterationCommunityBadges[0]?.tokenId : undefined;
    await executeVote(votingRole, project.address, tokenId, refreshVotingData);
  }

  // Get network-specific values
  const network = $derived(chainId ? NETWORKS[chainId] : null);
  const mintAmount = $derived(network?.mintAmount ?? '30');
  const tokenSymbol = $derived(network?.tokenSymbol ?? 'TSYS');

  // Determine header role tag
  const headerRoleTag = $derived.by(() => {
    if (roles.devrel) return { label: ROLE_LABELS.devrel, color: ROLE_COLORS.devrel };
    if (roles.dao_hic) return { label: ROLE_LABELS.dao_hic, color: ROLE_COLORS.dao_hic };
    if (roles.community || (!roles.project && !isOwner)) {
      return { label: ROLE_LABELS.community, color: ROLE_COLORS.community };
    }
    return null;
  });

  const hasJuryRole = $derived(roles.devrel || roles.dao_hic || roles.community);
  const canBecomeCommunity = $derived(!roles.project && !roles.devrel && !roles.dao_hic && !roles.community && !isOwner);
  const hasDevRelBadge = $derived(currentIterationBadges?.some(badge => badge.role === 'devrel') ?? false);
  const hasDaoHicBadge = $derived(currentIterationBadges?.some(badge => badge.role === 'dao_hic') ?? false);

  const canEditMetadata = $derived.by(() => {
    if (!project || !walletAddress) return false;
    if (!registryAvailable || initializationComplete === null) return false;

    const walletLower = walletAddress.toLowerCase();

    // Owner bypass
    const ownerBypassEnabled = import.meta.env.VITE_OWNER_METADATA_BYPASS === 'true';
    const isRegistryOwner = Boolean(registryOwner && walletLower === registryOwner.toLowerCase());

    if (ownerBypassEnabled && isRegistryOwner) {
      return true;
    }

    if (!initializationComplete) {
      return isRegistryOwner;
    }

    if (projectsLocked) return false;
    return walletLower === project.address.toLowerCase();
  });

  // Can see metadata status section: registry owner or project wallet
  const canSeeMetadataStatus = $derived.by(() => {
    if (!project || !walletAddress) return false;
    const walletLower = walletAddress.toLowerCase();
    const isRegistryOwner = Boolean(registryOwner && walletLower === registryOwner.toLowerCase());
    const isProjectWallet = walletLower === project.address.toLowerCase();
    return isRegistryOwner || isProjectWallet;
  });

  const projectName = $derived(project?.metadata?.name ?? `Project #${project?.id ?? 0}`);
  const embedUrl = $derived(getYouTubeEmbedUrl(project?.metadata?.yt_vid ?? null));
</script>

{#if loading}
  <div class="pob-stack">
    <p class="text-sm text-[var(--pob-text-muted)]">Loading project...</p>
  </div>
{:else if !project}
  <div class="pob-stack">
    <section class="pob-pane">
      <p class="text-sm text-[var(--pob-text-muted)]">Project not found.</p>
      <Link
        to={`/iteration/${currentIteration?.iteration ?? 1}`}
        class="pob-button pob-button--outline pob-button--compact"
        style="margin-top: 1rem; display: inline-flex;"
      >
        Back to Iteration
      </Link>
    </section>
  </div>
{:else}
  <!-- Main content -->
  <div class="pob-stack lg:pr-4" style={!sidebarVisible ? 'grid-column: 1 / -1;' : ''}>
    <!-- Back link -->
    <Link
      to={`/iteration/${currentIteration?.iteration ?? 1}`}
      class="text-sm text-[var(--pob-text-muted)] hover:text-[var(--pob-primary)]"
      style="display: inline-flex; align-items: center; gap: 0.5rem;"
    >
      ← Back to Projects
    </Link>

    <!-- Project card without vote button -->
    <section class="pob-pane">
      <div class="space-y-4">
        <div class="pob-pane__heading project-page__heading">
          <div>
            <h1 class="project-page__title">{projectName}</h1>
            <p class="pob-mono text-xs text-[var(--pob-text-muted)]">
              {formatAddress(project.address)}
            </p>
          </div>
          {#if canEditMetadata}
            <Link
              to={`/iteration/${currentIteration?.iteration}/project/${project.address}/edit`}
              class="pob-button pob-button--outline pob-button--compact project-page__edit"
            >
              Edit
            </Link>
          {/if}
        </div>

        <!-- Full description -->
        <div class="project-page__description">
          <MarkdownRenderer content={project.metadata?.description} />
        </div>

        <!-- Video embed -->
        {#if embedUrl}
          <div class="pob-video" style="margin-top: 1.5rem; margin-bottom: 1rem;">
            <iframe
              src={embedUrl}
              title={`Project video for ${projectName}`}
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              allowfullscreen
            ></iframe>
          </div>
        {/if}

        <!-- Proposal link -->
        {#if project.metadata?.proposal}
          <div style="margin-top: 1rem;">
            <a
              href={project.metadata.proposal}
              target="_blank"
              rel="noopener noreferrer"
              class="pob-button pob-button--outline pob-button--compact"
            >
              Read full proposal
            </a>
          </div>
        {/if}

        <!-- Social links + on-chain metadata links -->
        <div class="pob-socials" style="margin-top: 1.5rem;">
          <!-- Social links on the left -->
          {#if project.metadata?.socials?.x}
            <a
              href={project.metadata.socials.x}
              target="_blank"
              rel="noopener noreferrer"
              class="pob-socials__link pob-socials__link--x"
              title="X (Twitter)"
            >
              X
            </a>
          {/if}
          {#if project.metadata?.socials?.instagram}
            <a
              href={project.metadata.socials.instagram}
              target="_blank"
              rel="noopener noreferrer"
              class="pob-socials__link"
              title="Instagram"
            >
              Instagram
            </a>
          {/if}
          {#if project.metadata?.socials?.tiktok}
            <a
              href={project.metadata.socials.tiktok}
              target="_blank"
              rel="noopener noreferrer"
              class="pob-socials__link"
              title="TikTok"
            >
              TikTok
            </a>
          {/if}
          {#if project.metadata?.socials?.linkedin}
            <a
              href={project.metadata.socials.linkedin}
              target="_blank"
              rel="noopener noreferrer"
              class="pob-socials__link"
              title="LinkedIn"
            >
              LinkedIn
            </a>
          {/if}

          <!-- Spacer to push on-chain links to the right -->
          <span style="flex: 1;"></span>

          <!-- On-chain metadata links on the right -->
          {#if currentCID}
            <a
              href={getMetadataCidUrl(currentCID)}
              target="_blank"
              rel="noopener noreferrer"
              class="pob-socials__link"
              title={`IPFS CID: ${currentCID}`}
            >
              📦 IPFS
            </a>
          {/if}
          {#if currentTxHash && iterationChainId}
            <a
              href={getExplorerTxLink(iterationChainId, currentTxHash)}
              target="_blank"
              rel="noopener noreferrer"
              class="pob-socials__link"
              title={`Transaction: ${currentTxHash}`}
            >
              ⛓️ TX
            </a>
          {/if}
        </div>

        <!-- Metadata Status Section - visible to owner/project wallet only -->
        {#if canSeeMetadataStatus && pendingCID}
          {#if !currentCID}<div class="pob-pane__divider"></div>{/if}
          <div class="pob-stack--dense" style={currentCID ? 'margin-top: 0.75rem;' : ''}>
            <p class="pob-pane__meta">Update Status</p>
            <div class="flex items-center gap-3 text-xs">
              <a
                href={getMetadataCidUrl(pendingCID)}
                target="_blank"
                rel="noopener noreferrer"
                class="text-[var(--pob-primary)] hover:underline"
                title={`Pending CID: ${pendingCID}`}
              >
                📦 IPFS
              </a>
              {#if pendingTxHash && iterationChainId}
                <a
                  href={getExplorerTxLink(iterationChainId, pendingTxHash)}
                  target="_blank"
                  rel="noopener noreferrer"
                  class="text-[var(--pob-primary)] hover:underline"
                  title={`Transaction: ${pendingTxHash}`}
                >
                  🔗 TX
                </a>
              {/if}
              <span class="pob-pill flex items-center gap-1">
                <ProgressSpinner size={16} progress={Math.min((pendingConfirmations / 5) * 100, 100)} />
                {pendingConfirmations}/5
              </span>
            </div>
          </div>
        {/if}
      </div>
    </section>
  </div>

  <!-- Sidebar with voting panel -->
  {#if sidebarVisible}
    <div class="pob-stack lg:pl-4">
      <!-- Jury Panel - Vote for this specific project -->
      {#if (hasJuryRole || canBecomeCommunity) && !isOwner}
        <section class="pob-pane">
          <div class="pob-pane__heading">
            <h3 class="pob-pane__title">Jury Panel</h3>
            {#if headerRoleTag}
              <span class={`pob-pill ${headerRoleTag.color}`}>
                {headerRoleTag.label}
              </span>
            {/if}
          </div>

          <div class="space-y-3">
            <!-- DevRel Role -->
            {#if roles.devrel}
              <p class="text-sm text-[var(--pob-text-muted)]">
                As DevRel, cast your vote for <span class="font-semibold text-white">{projectName}</span>.
              </p>
              {#if devRelVote}
                <p class="text-sm text-[var(--pob-text-muted)]">
                  Currently voted for{' '}
                  <span class="italic">
                    {getProjectLabel(devRelVote) ?? 'Unknown project'}
                  </span>
                </p>
              {/if}
              {#if canVote}
                <button
                  type="button"
                  onclick={handleVote}
                  disabled={pendingAction !== null}
                  class="pob-button w-full justify-center"
                >
                  {hasVotedForThisProject ? 'Voted' : hasVotedAnywhere ? 'Change Vote' : 'Vote'}
                </button>
              {/if}
              {#if !hasDevRelBadge && statusFlags.votingEnded}
                <button
                  type="button"
                  onclick={() => void executeMint('devrel', refreshBadges)}
                  class="pob-button pob-button--outline w-full justify-center text-xs"
                  disabled={pendingAction !== null || !walletAddress}
                >
                  Mint DevRel badge
                </button>
              {/if}
            {/if}

            <!-- DAO HIC Role -->
            {#if roles.dao_hic}
              <p class="text-sm text-[var(--pob-text-muted)]">
                As a DAO HIC voter, cast your vote for <span class="font-semibold text-white">{projectName}</span>.
              </p>
              {#if daoHicVote}
                <p class="text-sm text-[var(--pob-text-muted)]">
                  Currently voted for{' '}
                  <span class="italic">
                    {getProjectLabel(daoHicVote) ?? 'Unknown project'}
                  </span>
                </p>
              {/if}
              {#if canVote}
                <button
                  type="button"
                  onclick={handleVote}
                  disabled={pendingAction !== null}
                  class="pob-button w-full justify-center"
                >
                  {hasVotedForThisProject ? 'Voted' : hasVotedAnywhere ? 'Change Vote' : 'Vote'}
                </button>
              {/if}
              {#if !hasDaoHicBadge && statusFlags.votingEnded}
                <button
                  type="button"
                  onclick={() => void executeMint('dao_hic', refreshBadges)}
                  class="pob-button pob-button--outline w-full justify-center text-xs"
                  disabled={pendingAction !== null || !walletAddress}
                >
                  Mint DAO HIC badge
                </button>
              {/if}
            {/if}

            <!-- Community Role -->
            {#if roles.community || canBecomeCommunity}
              <p class="text-sm text-[var(--pob-text-muted)]">
                {#if hasVotedAnywhere}
                  Currently voted for{' '}
                  <span class="italic">
                    {getProjectLabel(currentIterationCommunityBadges.find(b => b.hasVoted)?.vote ?? null) ?? 'Unknown'}
                  </span>
                {:else}
                  Vote for <span class="font-semibold text-white">{projectName}</span>.
                {/if}
              </p>
              {#if statusFlags.isActive && !statusFlags.votingEnded && walletAddress}
                <button
                  type="button"
                  onclick={handleVoteClick}
                  disabled={pendingAction !== null}
                  class="pob-button w-full justify-center"
                >
                  {hasVotedForThisProject ? 'Voted' : hasVotedAnywhere ? 'Change Vote' : 'Vote'}
                </button>
              {/if}
              {#if statusFlags.isActive}
                <p class="text-xs text-[var(--pob-text-muted)] italic">
                  You can change your vote at any time during the voting period.
                </p>
              {/if}
            {/if}

            <!-- Voting ended message -->
            {#if statusFlags.votingEnded}
              <p class="text-xs text-[var(--pob-text-muted)] italic">
                Voting has ended for this iteration.
              </p>
            {/if}

            <!-- Not active yet -->
            {#if !statusFlags.isActive && !statusFlags.votingEnded}
              <p class="text-xs text-[var(--pob-text-muted)] italic">
                Voting has not started yet.
              </p>
            {/if}
          </div>
        </section>
      {/if}

      <!-- Owner message -->
      {#if isOwner}
        <section class="pob-pane">
          <div class="pob-pane__heading">
            <h3 class="pob-pane__title">Owner View</h3>
          </div>
          <p class="text-sm text-[var(--pob-text-muted)]">
            As the contract owner, you cannot vote on projects.
          </p>
        </section>
      {/if}

      <!-- Project participant message -->
      {#if roles.project && !isOwner}
        <section class="pob-pane">
          <div class="pob-pane__heading">
            <h3 class="pob-pane__title">Participant View</h3>
          </div>
          <p class="text-sm text-[var(--pob-text-muted)]">
            As a project participant, you cannot vote on projects.
          </p>
        </section>
      {/if}
    </div>
  {/if}

  <!-- Mobile toggle for sidebar -->
  {#if !sidebarVisible && (hasJuryRole || canBecomeCommunity) && !isOwner}
    <button
      type="button"
      onclick={() => sidebarVisible = true}
      class="pob-button pob-button--outline"
      style="position: fixed; bottom: 1rem; right: 1rem; z-index: 50;"
    >
      Vote
    </button>
  {/if}

  <!-- Vote Confirmation Modal -->
  {#if project && showVoteModal}
    <VoteConfirmationModal
      isOpen={true}
      onClose={() => showVoteModal = false}
      onConfirm={handleConfirmVote}
      {projectName}
      projectAddress={project.address}
      {votingRole}
      hasVotedForProject={hasVotedForThisProject}
      hasBadge={currentIterationBadges.length > 0}
      {executeMint}
      {refreshBadges}
      isPending={pendingAction !== null}
      {mintAmount}
      {tokenSymbol}
    />
  {/if}
{/if}
